package com.nms.common.domain;

public enum AuditEventType {
    NOTIFICATION_ACCEPTED,
    NOTIFICATION_REJECTED,
    DUPLICATE_SUBMISSION,
    ROUTING_DECIDED,
    DELIVERY_QUEUED,
    DELIVERY_ATTEMPTED,
    DELIVERY_SUCCEEDED,
    DELIVERY_FAILED,
    RETRY_SCHEDULED,
    DELIVERY_EXPIRED
}
